### ISSUE TITLE
请问如何识别含有中文信息的二维码？

### ISSUE THREAD

**Issue by zwmin** [shiwenna/jsqrcode#1]
现在识别出来是乱码

**Comment by shiwenna** [comment]
是的，对中文识别的兼容性并不好。这是zxing作者的[回复](https://github.com/zxing/zxing/issues/708)
或者你可以试一下[jsQR](https://github.com/cozmo/jsQR)，能识别中文。

**Comment by zwmin** [comment]
我查到了一个解决办法，在你这个基础上修改qrcode.js，将qrcode.process里面的return语句 改成
`var abcdefg =  qrcode.decode_utf8(str);
    return qrcode.utf8to16(abcdefg);`

然后再添加一个方法，就行了
`qrcode.utf8to16 = function(str) {
    var out, i, len, c;
    var char2, char3;
    out = '';
    len = str.length;
    i = 0;
    while (i < len) {
        c = str.charCodeAt(i++);
        switch (c >> 4) {

            case 0: case 1: case 2: case 3: case 4: case 5: case 6: case 7:
            // 0xxxxxxx
            out += str.charAt(i - 1);
            break;
            case 12: case 13:
            // 110x xxxx   10xx xxxx
            char2 = str.charCodeAt(i++);
            out += String.fromCharCode(((c & 0x1F) << 6) | (char2 & 0x3F));
            break;
            case 14:
                // 1110 xxxx  10xx xxxx  10xx xxxx
                char2 = str.charCodeAt(i++);
                char3 = str.charCodeAt(i++);
                out += String.fromCharCode(((c & 0x0F) << 12) |
                    ((char2 & 0x3F) << 6) |
                    ((char3 & 0x3F) << 0));
                break;
        }
    }
    return out;
}`

**Comment by shiwenna** [comment]
好的，谢谢！之前没考虑中文的情况，我会维护一下。
